# https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/go/README.md#configuration-file

version: 1
env:
  - CGO_ENABLED=0
flags:
  - -trimpath
goos: linux
goarch: arm64
dir: ./cmd/protoc-gen-go-vsrpc
binary: protoc-gen-go-vsrpc-{{ .Os }}-{{ .Arch }}
ldflags:
  - "-X main.Version={{ .Env.VERSION }}"
  - "-X main.Commit={{ .Env.COMMIT }}"
  - "-X main.CommitDate={{ .Env.COMMIT_DATE }}"
  - "-X main.TreeState={{ .Env.TREE_STATE }}"
