// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.22.3
// source: vsrpc/vsrpc_test.proto

package vsrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input []int32 `protobuf:"varint,1,rep,packed,name=input,proto3" json:"input,omitempty"`
}

func (x *SumRequest) Reset() {
	*x = SumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vsrpc_vsrpc_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumRequest) ProtoMessage() {}

func (x *SumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vsrpc_vsrpc_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumRequest.ProtoReflect.Descriptor instead.
func (*SumRequest) Descriptor() ([]byte, []int) {
	return file_vsrpc_vsrpc_test_proto_rawDescGZIP(), []int{0}
}

func (x *SumRequest) GetInput() []int32 {
	if x != nil {
		return x.Input
	}
	return nil
}

type SumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Output int32 `protobuf:"varint,1,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *SumResponse) Reset() {
	*x = SumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vsrpc_vsrpc_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumResponse) ProtoMessage() {}

func (x *SumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vsrpc_vsrpc_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumResponse.ProtoReflect.Descriptor instead.
func (*SumResponse) Descriptor() ([]byte, []int) {
	return file_vsrpc_vsrpc_test_proto_rawDescGZIP(), []int{1}
}

func (x *SumResponse) GetOutput() int32 {
	if x != nil {
		return x.Output
	}
	return 0
}

var File_vsrpc_vsrpc_test_proto protoreflect.FileDescriptor

var file_vsrpc_vsrpc_test_proto_rawDesc = []byte{
	0x0a, 0x16, 0x76, 0x73, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x73, 0x72, 0x70, 0x63, 0x5f, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x76, 0x73, 0x72, 0x70, 0x63, 0x22,
	0x22, 0x0a, 0x0a, 0x53, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e,
	0x70, 0x75, 0x74, 0x22, 0x25, 0x0a, 0x0b, 0x53, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x68, 0x72, 0x6f, 0x6e, 0x6f, 0x73,
	0x2d, 0x74, 0x61, 0x63, 0x68, 0x79, 0x6f, 0x6e, 0x2f, 0x76, 0x73, 0x72, 0x70, 0x63, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vsrpc_vsrpc_test_proto_rawDescOnce sync.Once
	file_vsrpc_vsrpc_test_proto_rawDescData = file_vsrpc_vsrpc_test_proto_rawDesc
)

func file_vsrpc_vsrpc_test_proto_rawDescGZIP() []byte {
	file_vsrpc_vsrpc_test_proto_rawDescOnce.Do(func() {
		file_vsrpc_vsrpc_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_vsrpc_vsrpc_test_proto_rawDescData)
	})
	return file_vsrpc_vsrpc_test_proto_rawDescData
}

var file_vsrpc_vsrpc_test_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vsrpc_vsrpc_test_proto_goTypes = []interface{}{
	(*SumRequest)(nil),  // 0: vsrpc.SumRequest
	(*SumResponse)(nil), // 1: vsrpc.SumResponse
}
var file_vsrpc_vsrpc_test_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vsrpc_vsrpc_test_proto_init() }
func file_vsrpc_vsrpc_test_proto_init() {
	if File_vsrpc_vsrpc_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vsrpc_vsrpc_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vsrpc_vsrpc_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vsrpc_vsrpc_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vsrpc_vsrpc_test_proto_goTypes,
		DependencyIndexes: file_vsrpc_vsrpc_test_proto_depIdxs,
		MessageInfos:      file_vsrpc_vsrpc_test_proto_msgTypes,
	}.Build()
	File_vsrpc_vsrpc_test_proto = out.File
	file_vsrpc_vsrpc_test_proto_rawDesc = nil
	file_vsrpc_vsrpc_test_proto_goTypes = nil
	file_vsrpc_vsrpc_test_proto_depIdxs = nil
}
